### PR TITLE
Improvement/gridstack layout

### PR DESCRIPTION
**Pull request by rclagett**

### CODE REVIEW

**Review by Grumblesmith — CHANGES_REQUESTED** [review]
Is this 1.1.0 or 1.2.0?

**Comment by rclagett** [comment]
I think it should be 1.1.0, right? 1.0.1 -> 1.1.0

**Comment by markstarbuck** [comment]
1.1.0 is right to me.

**Comment by Grumblesmith** [comment]
@rclag1126 in that case, please update the README.md to that effect.

**Review by Grumblesmith — APPROVED** [review]

**Pull request merged**
